[package]
name = "adventofcode2023"
version = "0.1.0"
edition = "2021"
default-run = "inputs"

[dependencies]
anyhow = "1.0.75"
array2d = "0.3.1"
itertools = "0.12.0"
minreq = { version = "2.11.0", features = ["https-native"] }
regex = "1.10.2"
